// Generates a downloadable .docx report from a Talent Management analysis
// result, using the 'docx' library entirely client-side — no server round
// trip, consistent with the phase-1 "no backend beyond the AI calls"
// principle. Matches Lawrence's default report format (.docx).

import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx'

const severityLabel = { high: 'HIGH', medium: 'MEDIUM', low: 'LOW' }

export async function buildTalentReportDocx({ result, filterLabel, recordCount }) {
  const dateStr = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })

  const flagParagraphs = (result.flags || []).flatMap((flag) => [
    new Paragraph({
      spacing: { before: 200, after: 60 },
      children: [
        new TextRun({ text: `[${severityLabel[flag.severity] || flag.severity?.toUpperCase() || ''}] `, bold: true }),
        new TextRun({ text: flag.type, bold: true }),
      ],
    }),
    new Paragraph({
      spacing: { after: 40 },
      children: [new TextRun({ text: flag.detail })],
    }),
    ...(flag.site
      ? [new Paragraph({
          spacing: { after: 100 },
          children: [new TextRun({ text: flag.site, italics: true, color: '71717A' })],
        })]
      : []),
  ])

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            heading: HeadingLevel.TITLE,
            children: [new TextRun({ text: 'Talent Management — Consistency & Calibration Report' })],
          }),
          new Paragraph({
            spacing: { after: 200 },
            children: [
              new TextRun({ text: `Prepared by InsightFlow · ${dateStr}`, color: '71717A', size: 20 }),
            ],
          }),
          new Paragraph({
            spacing: { after: 300 },
            children: [
              new TextRun({
                text: `Scope: ${filterLabel} · ${recordCount} record${recordCount === 1 ? '' : 's'} analysed`,
                color: '71717A', size: 20,
              }),
            ],
          }),
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 200, after: 120 },
            children: [new TextRun({ text: `Flagged Items (${result.flags?.length || 0})` })],
          }),
          ...flagParagraphs,
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 300, after: 120 },
            children: [new TextRun({ text: 'Leadership Summary' })],
          }),
          new Paragraph({
            children: [new TextRun({ text: result.narrative || 'No summary generated.' })],
          }),
          new Paragraph({
            spacing: { before: 400 },
            alignment: AlignmentType.LEFT,
            children: [
              new TextRun({
                text: 'Generated by InsightFlow — SynerGrowth Consulting. Phase 1: manual document analysis, no connection to any live HR or payroll system.',
                italics: true, size: 16, color: 'A1A1AA',
              }),
            ],
          }),
        ],
      },
    ],
  })

  const blob = await Packer.toBlob(doc)
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `InsightFlow-Talent-Report-${new Date().toISOString().slice(0, 10)}.docx`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
