// Generates a downloadable .docx from one or more onboarding plans,
// client-side, no server round trip.

import { Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx'

const sectionLabels = { preboarding: 'Pre-boarding', day1: 'Day 1', week1: 'Week 1', month1: 'Month 1' }

export async function buildOnboardingReportDocx(plans) {
  const dateStr = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })

  const planSections = plans.flatMap((plan, i) => [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      spacing: { before: i === 0 ? 100 : 400, after: 120 },
      children: [new TextRun({ text: `${plan.role} — ${plan.level} — ${plan.site}` })],
    }),
    ...Object.keys(sectionLabels).flatMap((key) => {
      const tasks = plan.checklist?.[key] || []
      if (!tasks.length) return []
      return [
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 160, after: 80 },
          children: [new TextRun({ text: sectionLabels[key] })],
        }),
        ...tasks.map((t) => new Paragraph({ bullet: { level: 0 }, children: [new TextRun({ text: t })] })),
      ]
    }),
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 200, after: 80 },
      children: [new TextRun({ text: 'Manager Brief' })],
    }),
    new Paragraph({ children: [new TextRun({ text: plan.managerBrief || 'No brief generated.' })] }),
  ])

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({ heading: HeadingLevel.TITLE, children: [new TextRun({ text: 'Onboarding Plan(s)' })] }),
          new Paragraph({ spacing: { after: 300 }, children: [new TextRun({ text: `Prepared by InsightFlow · ${dateStr} · ${plans.length} plan(s)`, color: '71717A', size: 20 })] }),
          ...planSections,
          new Paragraph({
            spacing: { before: 400 },
            children: [new TextRun({
              text: 'Generated by InsightFlow — SynerGrowth Consulting. Phase 1: manual document analysis, no connection to any live HR or payroll system.',
              italics: true, size: 16, color: 'A1A1AA',
            })],
          }),
        ],
      },
    ],
  })

  const blob = await Packer.toBlob(doc)
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `InsightFlow-Onboarding-${new Date().toISOString().slice(0, 10)}.docx`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
