// Generates a downloadable .docx report from a Workforce Insights view,
// client-side, no server round trip.

import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType } from 'docx'

function distTable(data) {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Category', bold: true })] })] }),
          new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: 'Count', bold: true })] })] }),
        ],
      }),
      ...data.map((d) => new TableRow({
        children: [
          new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: d.name })] })] }),
          new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: String(d.value) })] })] }),
        ],
      })),
    ],
  })
}

export async function buildWorkforceReportDocx({ scope, recordCount, ageData, genderData, tenureData, attritionRate, leaverCount, summary }) {
  const dateStr = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({ heading: HeadingLevel.TITLE, children: [new TextRun({ text: 'Workforce Insights Report' })] }),
          new Paragraph({ spacing: { after: 100 }, children: [new TextRun({ text: `Prepared by HRinsight · ${dateStr}`, color: '71717A', size: 20 })] }),
          new Paragraph({ spacing: { after: 300 }, children: [new TextRun({ text: `Scope: ${scope} · ${recordCount} record(s) with demographic data`, color: '71717A', size: 20 })] }),

          ...(attritionRate != null ? [
            new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 100, after: 80 }, children: [new TextRun({ text: 'Attrition' })] }),
            new Paragraph({ spacing: { after: 200 }, children: [new TextRun({ text: `${attritionRate}% (${leaverCount} left this cycle). Defined as leavers ÷ (active + leavers) × 100 — a simplified phase-1 proxy, not official HR methodology.` })] }),
          ] : []),

          new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 100, after: 120 }, children: [new TextRun({ text: 'Age Distribution' })] }),
          distTable(ageData),

          new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 300, after: 120 }, children: [new TextRun({ text: 'Gender Mix' })] }),
          distTable(genderData),

          new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 300, after: 120 }, children: [new TextRun({ text: 'Years of Service' })] }),
          distTable(tenureData),

          new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 300, after: 120 }, children: [new TextRun({ text: 'AI Summary' })] }),
          new Paragraph({ children: [new TextRun({ text: summary || 'No summary generated for this view.' })] }),

          new Paragraph({
            spacing: { before: 400 },
            children: [new TextRun({
              text: 'Generated by HRinsight — SynerGrowth Consulting. Phase 1: manual document analysis, no connection to any live HR or payroll system. Only aggregated counts were used — no individual employee data.',
              italics: true, size: 16, color: 'A1A1AA',
            })],
          }),
        ],
      },
    ],
  })

  const blob = await Packer.toBlob(doc)
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `HRinsight-Workforce-Report-${new Date().toISOString().slice(0, 10)}.docx`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
