// Exports the current Admin Services Q&A conversation as a .docx transcript,
// client-side, no server round trip.

import { Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx'

export async function buildChatTranscriptDocx(messages) {
  const dateStr = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })

  const turns = messages.flatMap((m) => [
    new Paragraph({
      spacing: { before: 160, after: 40 },
      children: [new TextRun({ text: m.role === 'user' ? 'Question' : 'Answer', bold: true, color: m.role === 'user' ? '3b82f6' : '111113' })],
    }),
    new Paragraph({ children: [new TextRun({ text: m.content })] }),
  ])

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({ heading: HeadingLevel.TITLE, children: [new TextRun({ text: 'Admin Services — Q&A Transcript' })] }),
          new Paragraph({ spacing: { after: 300 }, children: [new TextRun({ text: `Prepared by InsightFlow · ${dateStr}`, color: '71717A', size: 20 })] }),
          ...turns,
          new Paragraph({
            spacing: { before: 400 },
            children: [new TextRun({
              text: 'Generated by InsightFlow — SynerGrowth Consulting. Answers are drawn from the current Document repository only.',
              italics: true, size: 16, color: 'A1A1AA',
            })],
          }),
        ],
      },
    ],
  })

  const blob = await Packer.toBlob(doc)
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `InsightFlow-AdminServices-Transcript-${new Date().toISOString().slice(0, 10)}.docx`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
